import Vue from 'vue'
import {XHeader, Actionsheet, ButtonTab, ButtonTabItem, ViewBox, Tabbar, Loading, Badge, TabbarItem, TabItem, XImg, XButton, Divider, Group, XInput, Cell, Sticky, Tab, Swiper, SwiperItem, Grid, GridItem, Flexbox, FlexboxItem, Checker, CheckerItem, Search, Scroller, LoadMore} from 'vux'

Vue.component('x-header', XHeader)
Vue.component('actionsheet', Actionsheet)
Vue.component('button-tab', ButtonTab)
Vue.component('button-tab-item', ButtonTabItem)
Vue.component('view-box', ViewBox)
Vue.component('tabbar', Tabbar)
Vue.component('tabbar-item', TabbarItem)
Vue.component('tab', Tab)
Vue.component('loading', Loading)
Vue.component('x-img', XImg)
Vue.component('badge', Badge)
Vue.component('x-button', XButton)
Vue.component('divider', Divider)
Vue.component('grid', Grid)
Vue.component('grid-item', GridItem)
Vue.component('sticky', Sticky)
Vue.component('group', Group)
Vue.component('x-input', XInput)
Vue.component('cell', Cell)
Vue.component('swiper', Swiper)
Vue.component('flexbox', Flexbox)
Vue.component('flexbox-item', FlexboxItem)
Vue.component('tab', Tab)
Vue.component('tab-item', TabItem)
Vue.component('swiper-item', SwiperItem)
Vue.component('checker', Checker)
Vue.component('checker-item', CheckerItem)
Vue.component('search', Search)
Vue.component('scroller', Scroller)
Vue.component('load-more', LoadMore)
